//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpensesTrackerAplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public int Id { get; set; }
        public string ProyectID { get; set; }
        public string Name { get; set; }
        public string ExpenseDate { get; set; }
        public string Amount { get; set; }
        public string Description { get; set; }
    }
}
